# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    automerge:
      enabled: true
      override_labels:
        - "automerge"
    review:
      require: true
      required_approvals: 1
          automerge:
      enabled: true
      labels:
        - "automerge"
      ignore:
        - "security"  # Optional: Ignore "security" label
    allow:
      - dependency-type: "all"
        auto-approve-reviewers: 1
